### ISSUE TITLE
multhithreading

### ISSUE THREAD

**Issue by xkr1se** [qamulex/EasyRateLimiter#1]
опкакается во многопотоке

**Comment by NaulbiMIX** [comment]
The repo utility does not assume the use of a specific multithread support.
The builder has a ["function-method" `useRequestAccumulator`](https://github.com/qamulex/EasyRateLimiter/blob/b6c06a5c25b1981dac7bb7a22dabbbfe0f62f948/src/main/java/me/qamulex/erl/SingleChannelRateLimiter.java#L170). It involves the use of thread-safe designs.

You can use standard mechanisms from Java and/or from any other libraries/platforms that you use. Let's assume that this is a Minecraft Java Edition server on a fork-kernel of the Bukkit, "which assumes its support for multithreads" (borrowed from Vanilla etc).

If you used this as a proxy server for the same Minecraft Java Edition, then why not use velocity and the popular LimboAuth plugin, which has something to optimize. [Example code using this util repo](https://github.com/Elytrium/LimboAuth/blob/2bdf4d9ac229fa9e37cb039edc7b8d18f57be8e8/src/main/java/net/elytrium/limboauth/LimboAuth.java#L149-L152). Not only MEMORY LEAKs (they are not fixed using garbage collectors even in aggressive mode).

**Comment by qamulex** [comment]
> опкакается во многопотоке

Нет.
