### ISSUE TITLE
shit code

### ISSUE THREAD

**Issue by katogiri** [qamulex/EasyRateLimiter#2]
код такой себе, рефактор нужен

**Comment by NaulbiMIX** [comment]
Will there be arguments for "shit code"?

If you use the kernel for the Minecraft Java Edition server original (Vanilla from Mojang) and have never patched it (NMS) and use additional modifications from forks, then you should ask yourself about using "shit kernel". (Examples)[https://imgur.com/a/atodl1Y].

Try to get a decompiled kernel and patched yourself using (BuildTools)[https://www.spigotmc.org/wiki/buildtools/] and make sure of it.
The sources used were also with patches (Paper)[https://github.com/PaperMC/Paper/tree/ver/1.12.2].

I note that decompilers for online viewing will not show unused code, use the decompilation process itself from more powerful decompilers (example: fernflower).

**Comment by qamulex** [comment]
> код такой себе, рефактор нужен

Not enough information.
